title: Yifei Huang
description: My Homepage
author: Yifei Huang
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/hyf015
about: PhD student @ UTokyo

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: hyf
google_analytics: UA-122681435-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
